// src/routes/Footer.svelte
<script lang="ts">
	import type { ComponentType } from 'svelte';
	import { IconEmail, IconInstagram, IconLinkedIn } from '../lib/components/icons';

	interface SocialLink {
		href: string;
		icon: ComponentType;
	}

	const socialLinks: SocialLink[] = [
		{
			href: 'https://www.instagram.com/iryna_lisogor/',
			icon: IconInstagram
		},
		{
			href: 'https://www.linkedin.com/in/iryna-lisogor-72975316a',
			icon: IconLinkedIn
		},
		{
			href: 'mailto:email@',
			icon: IconEmail
		}
	];
</script>

<footer class="w-full flex justify-center py-5 mt-5">
	<ul class="flex gap-4">
		{#each socialLinks as { href, icon } (href)}
			<li>
				<a {href}>
					<svelte:component this={icon} />
				</a>
			</li>
		{/each}
		<!-- <li>
			<a href="https://www.instagram.com/iryna_lisogor/">
				<IconInstagram />
			</a>
		</li>
		<li>
			<a href="https://www.linkedin.com/in/iryna-lisogor-72975316a">
				<IconLinkedIn />
			</a>
		</li>
		<li>
			<a href="mailto:email@">
				<IconEmail />
			</a>
		</li> -->
	</ul>
</footer>

// src/components/Footer.vue
<script>
import IconBehance from "./icons/IconBehance.vue";
import IconInstagram from "./icons/IconInstagram.vue";
import IconMail from "./icons/IconMail.vue";

export default {
  name: "AppFooter",
  components: {
    IconBehance,
    IconInstagram,
    IconMail,
  },
  computed: {
    fullYear() {
      return new Date().getFullYear();
    },
  },
};
</script>

<template>
  <footer class="footer">
    <div class="socials-list">
      <a href="https://www.instagram.com/iryna_lisogor/" target="_blank"
        ><IconInstagram :width="50"
      /></a>
      <a href="https://www.behance.net/lisogorka8741b" target="_blank"
        ><IconBehance :width="50"
      /></a>
      <a href="mailto:iryna.lisogor.artwrk@gmail.com" target="_blank"
        ><IconMail :width="50"
      /></a>
    </div>
    <div>
      <p>All artistic content Copyright &#169;</p>
      <p>{{ fullYear }} Iryna Lisogor, All rights</p>
    </div>
  </footer>
</template>

<style scoped lang="scss">
.footer {
  color: #96979a;
  font-size: 16px;
}
.socials-list {
  display: flex;
  gap: 18px;
  width: 100%;
  justify-content: flex-end;
}
</style>
