// src/components/widgets/Footer.vue
<script>
import { socialLinks } from "@/utils/consts";
import BaseLink from "../shared/BaseLink.vue";
import IconBehance from "../shared/icons/IconBehance.vue";
import IconInstagram from "../shared/icons/IconInstagram.vue";
import IconMail from "../shared/icons/IconMail.vue";

export default {
  name: "AppFooter",
  data() {
    return {
      socialLinks,
    };
  },
  components: {
    IconBehance,
    IconInstagram,
    IconMail,
    BaseLink,
  },
  computed: {
    fullYear() {
      return new Date().getFullYear();
    },
  },
};
</script>

<template>
  <footer class="footer">
    <div class="socials-list">
      <BaseLink v-for="link in socialLinks" :key="link.href" :href="link.href">
        <component :is="link.component" :width="50" />
      </BaseLink>
    </div>
    <div>
      <p>All artistic content Copyright &#169;</p>
      <p>{{ fullYear }} Iryna Lisogor, All rights</p>
    </div>
  </footer>
</template>

<style scoped lang="scss">
.footer {
  color: #96979a;
  font-size: 16px;
}

.socials-list {
  display: flex;
  gap: 18px;
  width: 100%;
  justify-content: flex-end;
}
</style>

// src/lib/components/Footer.svelte
<script lang="ts">
	import SocialsNavigation from '$lib/components/SocialsNavigation.svelte';
	import { socialLinksList } from '$lib/data/socialLinksList';
	import { fullYear } from '$lib/utils';
</script>

<footer class="wrapper">
	<div class="footer__socials-nav">
		<SocialsNavigation list={socialLinksList} />
	</div>
	<p>
		All artistic content Copyright &#169;<br />
		{fullYear()} Iryna Lisogor, All rights
	</p>
</footer>

<style lang="scss">
	.wrapper {
		font-size: var(--size-step--3);
		margin: var(--space-l-3xl) auto var(--space-s);
		text-align: center;
	}

	.footer__socials-nav {
		display: flex;
		justify-content: center;
		margin-bottom: var(--space-s);

		@include respond-to('m') {
			display: none;
		}
	}
</style>
